#!/bin/bash

PARCHMENT_GIT="git://github.com/curiousdannii/parchment.git"
DROPBOX=~/Dropbox
SLIDES=ttmb_media

rm -rf $DEST

function die {
	 echo "PROBLEMS $1"
	 exit 1
}

if [ "$(which npm)" == "" ] || [ "$(which node)" == "" ] ; then
   die "requires nodejs!"
fi

if [ "$(which grunt)" == "" ] ; then
   die "requires grunt!"
fi

# fetch parchment!
if [ -e "parchment" ] ; then
   cd parchment && git pull && cd .. || die "unable to clone parchment!"
else
   git clone $PARCHMENT_GIT parchment || die "unable to pull parchment!"
fi

# build parchment!
cd parchment && \
npm install && \
grunt && \
cd .. || die "unable to build parchment!"

# generate ttmb_slides
SLIDES_FILE=src/js/ttmb_slides.js
DIRECTORY=${DROPBOX}/TribesThatMayBe/${SLIDES}

echo -n "var imageList = [ " > $SLIDES_FILE
FIRST=true
F_ARG="-type f"
if [ "$(uname)" == "Darwin" ] ; then
	F_ARG="-type file"
fi

for f in $(find ${DIRECTORY} ${F_ARG}) ; do
    if [ $FIRST == true ] ; then
        FIRST=false
    else
        echo -n "," >> $SLIDES_FILE
    fi
    echo -n "\"$(basename $f)\"" >> $SLIDES_FILE
done
echo  "];" >> $SLIDES_FILE
echo "built slideshow js"
