---
- hosts: raspi
  vars:
  - cfile: ~/Dropbox/TribesThatMayBe/typical.yml
  vars_files:
  - $cfile
  tasks:
  - include: tasks/preflight.yml
  - include: tasks/base.yml
  - include: tasks/trim.yml
  - include: tasks/security.yml
  - include: tasks/monit.yml
  - include: tasks/collectd.yml
  - include: tasks/hostapd.yml
  - include: tasks/networking.yml
  - include: tasks/dnsmasq.yml
  - include: tasks/nginx-raspi.yml
  - include: tasks/tribes.yml dest=/opt/ttmb/ source=raspi.html story=$raspi_story
  - include: tasks/slideshow.yml dest=/opt/ttmb/slideshow
