---
- name: base | ansible deps
  command: apt-get -y install python-apt creates=/usr/share/doc/python-apt
- name: base | create apt-update-post-invoke-success hook
  copy: src=conf/apt-touchstamp.conf dest=/etc/apt/apt.conf.d/90-touchstamp
- name: base | copy apt-touchstamp helper script
  copy: src=bin/apt-touchstamp.sh dest=/usr/local/sbin/apt-touchstamp mode=0770 force=true
- name: base | check last apt-update
  register: last_apt_update
  command: /usr/local/sbin/apt-touchstamp
- name: base | update apt cache
  apt: update_cache=yes
  only_if: "'${last_apt_update.stdout}' == 'true'"
- name: base | install dependencies
  apt: pkg=$item state=latest
  only_if: "'${last_apt_update.stdout}' == 'true'"
  with_items:
    - vim
    - sudo
    - build-essential
    - nginx
    - python-httplib2
    - dnsmasq
    - iw
- name: base | remove unnecesary packages
  apt: pkg=$item state=absent
  with_items:
  - xserver-common
  - xserver-xorg
  - xserver-xorg-core
  - xserver-xorg-input-all
  - xserver-xorg-input-evdev
  - xserver-xorg-input-synaptics
  - xserver-xorg-video-fbdev
  - zenity
  - zenity-commont
  - x11-common
  - x11-utils
  - x11-xkb-util
  - xarchiver
  - xauth
  - xdg-utils
  - xfonts-encodings
  - xfonts-utils
  - xinit
  - xkb-data
  - xpdf
  - wpagui
  - tk8.5
  - penguinspuzzle
  - netsurf-common
  - netsurf-gtk
  - midori
  - menu-xdg
  - lxde
  - lxde-common
  - lxde-core
  - lxde-icon-theme
  - lxinput
  - lxmenu-data
  - lxpanel
  - lxpolkit
  - lxrandr
  - lxsession
  - lxsession-edit
  - lxshortcut
  - lxtask
  - lxterminal
  - lxappearance
  - dbus-x11
  - desktop-base
  - desktop-file-utils
  - gnome-accessibility-themes
  - gnome-icon-theme
  - gnome-themes-standard
  - gnome-themes-standard-data
  - gsettings-desktop-schemas
  - gsfonts-x11
  - gtk2-engines:armhf
  - hicolor-icon-theme
  - squeak-vm
  - xterm