---
  - name: hostapd | fetch hostapd-rtl8188
    uri: dest=/tmp url=https://github.com/jenssegers/RTL8188-hostapd/archive/master.zip creates=/tmp/master.zip
  - name: hostapd | extract hostapd-rtl8188
    command: unzip /tmp/master.zip creates=/tmp/RTL8188-hostapd-master chdir=/tmp
  - name: hostapd | build
    command: make chdir=/tmp/RTL8188-hostapd-master/hostapd creates=/tmp/RTL8188-hostapd-master/hostapd/hostapd
  - name: hostapd | install
    command: make install chdir=/tmp/RTL8188-hostapd-master/hostapd creates=/usr/local/bin/hostapd
  - name: hostapd | copy config file
    copy: src=conf/hostapd.conf dest=/etc/hostapd/hostapd.conf
