---
- name: collectd | check if collectd is installed
  command: /usr/local/bin/is_installed apt collectd-core
  register: collectd_installed
  changed_when: false
- name: collectd | must be installed if offline
  fail: msg="Collectd not installed but not online"
  when: collectd_installed.stdout == '0' and am_online.stdout != '0'
  changed_when: false
- name: collectd | install packages
  apt: pkg="{{item}}" state=latest install_recommends=no
  when: am_online.stdout == '0'
  with_items:
  - collectd-core
- name: collectd | copy config file
  copy: src=collectd.conf dest=/etc/collectd/collectd.conf force=yes
- name: collectd | copy exec scripts
  copy: src="{{item}}" dest="/usr/local/bin/{{item}}" mode=0755 force=yes
  with_items:
  - collectd_hostapd
  - collectd_thermal
- name: collectd | copy python plugins
  copy: src="{{item}}" dest="/usr/local/lib/{{item}}" mode=0755 force=yes
  with_items:
  - sensors_collectd.py
- name: collectd | restart service
  service: name=collectd state=restarted