---
- name: monit | check if monit is installed
  command: /usr/local/bin/is_installed apt monit
  register: monit_installed
- name: monit | must be installed if offline
  fail: msg="Monit not installed but not online"
  when: monit_installed.stdout == '0' and am_online.stdout != '0'
- name: monit | install package
  apt: pkg=monit state=latest
  when: am_online.stdout == '0'
- name: monit | install monitrc
  copy: src=monitrc dest=/etc/monit/monitrc force=yes
- name: monit | restart monit
  service: name=monit state=restarted