---
- name: slideshow | create directories
  file: path="{{dest}}/{{item}}" state=directory
  with_items:
  - js
  - images
- name: slideshow | copy js
  copy: src="./src/js/{{item}}" dest="{{dest}}/js" force=true
  with_items:
  - slideshow.js
  - jquery.flexslider-min.js
  - jquery.cookie.js
  - ttmb_slides.js
  - jquery.min.js
- name: slideshow | copy html
  copy: src=./src/slideshow.html dest="{{dest}}/index.html" force=true
- name: slideshow | copy images
  copy: src="{{item}}" dest="{{dest}}/images/" force=true
  with_fileglob:
  - "{{source_dir}}/{{slides}}/*"