- name: trim | remove unnecesary packages
  apt: pkg="{{item}}" state=absent purge=yes install_recommends=no
  with_items:
  - xserver-common
  - xserver-xorg
  - xserver-xorg-core
  - xserver-xorg-input-all
  - xserver-xorg-input-evdev
  - xserver-xorg-input-synaptics
  - xserver-xorg-video-fbdev
  - zenity
  - zenity-common
  - x11-common
  - x11-utils
  - x11-xkb-utils
  - xarchiver
  - xauth
  - xdg-utils
  - xfonts-encodings
  - xfonts-utils
  - xinit
  - xkb-data
  - xpdf
  - wpagui
  - tk8.5
  - penguinspuzzle
  - netsurf-common
  - netsurf-gtk
  - midori
  - dillo
  - menu-xdg
  - lxde
  - lxde-common
  - lxde-core
  - lxde-icon-theme
  - lxinput
  - lxmenu-data
  - lxpanel
  - lxpolkit
  - lxrandr
  - lxsession
  - lxsession-edit
  - lxshortcut
  - lxtask
  - lxterminal
  - lxappearance
  - dbus-x11
  - desktop-base
  - desktop-file-utils
  - gnome-accessibility-themes
  - gnome-icon-theme
  - gnome-themes-standard
  - gnome-themes-standard-data
  - gsettings-desktop-schemas
  - gsfonts-x11
  - gtk2-engines
  - hicolor-icon-theme
  - squeak-vm
  - xterm
  - gconf-service
  - gconf2-common
  - libxxf86vm1
  - libxxf86dga1
  - libxv1
  - libxrender1
  - libxrandr2
  - libxpm4
  - libxp6
  - libxmuu1
  - libxkbfile1
  - libxinerama1
  - libxi6
  - libxft2
  - libxfont1
  - libxfixes3
  - libxext6
  - libxdmcp6
  - libxdamage1
  - libxcursor1
  - libxcomposite1
  - libxcb1
  - libxcb-util0
  - libxcb-shm0
  - libxcb-shape0
  - libxcb-render0
  - libxcb-glx0
  - libxau6
  - libx11-xcb1
  - libx11-data
  - libx11-6
  - libwnck22
  - libwnck-common
  - libwibble-dev
  - libwebkitgtk-3.0-common
  - libwebkitgtk-1.0-common
  - libvte9
  - libvte-common
  - libusbmuxd1
  - libts-0.0-0
  - libqtdbus4
  - libqtcore4
  - libqt4-xml
  - libqt4-network
  - libplist1
  - libpciaccess0
  - libgtop2-7
  - libgtop2-common
  - libgtk2.0-common
  - libgtk2.0-bin
  - libgtk2.0-0
  - libgtk-3-common
  - libgtk-3-bin
  - libgtk-3-0
  - libgstreamer0.10-0
  - libgphoto2-port0
  - libgphoto2-2
  - libgnome-keyring0
  - libgnome-keyring-common
  - libglapi-mesa
  - libgl1-mesa-glx
  - libgdk-pixbuf2.0-common
  - libgdk-pixbuf2.0-0
  - libgconf-2-4
  - libgail18
  - libgail-3-0
  - libfontenc1
  - leafpad
  - pistore
  - squeak-plugins-scratch
  - smartsim
  - xfonts-encodings
  - gnome-icon-theme
  - gnome-themes-standard
  - gnome-themes-standard-data
  - gtk2-engines
  - gvfs-backends
  - gvfs-fuse
  - gpicview
  - gvfs-common
  - gvfs-daemons
  - gvfs-libs
  - gvfs
  - libaudio2
  - librsvg2-common
  - galculator
  - obconf
  - xarchiver
  - python-pygame
  - python-tk
  - python3-tk
  - poppler-utils
  - usbmuxd
  - libcairo2
  - libpango1.0-0
  - ghostscript
  - libpaper-utils
  - libpoppler19
  - dconf-gsettings-backend
  - dconf-service
  - libdconf0
  - glib-networking
  - glib-networking-common
  - glib-networking-services