#!/bin/bash
HOSTNAME="${COLLECTD_HOSTNAME:-localhost}"
INTERVAL="${COLLECTD_INTERVAL:-60}"

while sleep "$INTERVAL"; do
    CPUOUT=`cat /sys/class/thermal/thermal_zone0/temp`
    VALUE=`cut -c1-2 < << $CPUOUT`.`cut -c3-5 <<< $CPUOUT`
    echo "PUTVAL $HOSTNAME/pi/gauge-thermal interval=$INTERVAL N:$VALUE"
done
