---
- hosts: raspi
  vars:
  - cfile: ~/Dropbox/TribesThatMayBe/typical.yml
  vars_files:
  - $cfile
  tasks:
  - include: tasks/tribes.yml dest=/opt/ttmb source=raspi.html story=$raspi_story
  - include: tasks/slideshow.yml dest=/opt/ttmb/slideshow