---
- hosts: raspi
  vars_files:
  - ~/Dropbox/TribesThatMayBe/typical.yml
  tasks:
  - include: tasks/nginx-raspi.yml
  - include: tasks/tribes.yml dest=/opt/ttmb source="~/Dropbox/TribesThatMayBe/{{art_piece}}"
  - include: tasks/slideshow.yml dest=/opt/ttmb/slideshow
    when: with_slides == 'true'