---
- hosts: web
  vars:
  - cfile: ~/Dropbox/TribesThatMayBe/typical.yml
  vars_files:
  - $cfile
  tasks:
  - include: tasks/tribes.yml source=web.html story=$web_story
  - include: tasks/public.yml