---
- hosts: raspi
  vars_files:
  - ~/Dropbox/TribesThatMayBe/typical.yml
  tasks:
  - include: tasks/preflight.yml
  - include: tasks/base.yml
  - include: tasks/monit.yml
  - include: tasks/nginx-raspi.yml
  - include: tasks/tribes.yml dest=/opt/ttmb/ source=raspi.html source="~/Dropbox/TribesThatMayBe/{{art_piece}}"
